model:
  max_tokens: 800
  temperature: 0.7
prompt:
  system_role: You are a helpful assistant.
  user_prompt: 'Provide me answer based on the below context.

    Context: {context}

    Question: {question}

    If you are unable to answer based on the given context, please say "I don''t know".

    '
rag:
  chunk_overlap: 20
  chunk_size: 300
  index_name: ch3_data
  num_docs: 5